version: '3.4'

services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    container_name: vi-docker-test-nginx
    volumes:
      - ./:/app
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - internal
  php:
    build:
      context: ./docker
      dockerfile: php.docker
    container_name: vi-docker-test-php
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - internal
  mysql:
    build:
      context: ./docker
      dockerfile: mysql.docker
    container_name: vi-docker-test-mysql
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - internal
  adminer:
    image: adminer
    container_name: vi-docker-test-adminer
    ports:
      - 8089:8080
    depends_on:
      - mysql
    networks:
      - internal
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: ASMDIOEFNJLAWIENWAIEWQLKNWE
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "8085:15672"
      - "5672:5672"
    volumes:
      - ./docker/rabbit/plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - internal

volumes:
  db-volume:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/28